### ISSUE TITLE
Unify meta/settings files (e.g. times_mapping.txt and times-info.json)

### ISSUE THREAD

**Issue by siddharth-krishna** [etsap-TIMES/times-excel-reader#105]
Here's a proposal for how the combined mapping/category file could look. For the mapping `G_DRATE[REG,DATAYEAR,CUR,VALUE] = ~FI_T(Region,Year,Curr,VALUE,Attribute:G_DRATE)`, we could have the entry:
```yaml
- name: G_DRATE
  category: parameter
  times-cols:
    - REG
    - DATAYEAR
    - CUR
    - VALUE
  xl-cols:
    - Region
    - Year
    - Curr
    - VALUE
  filter-attribute: G_DRATE
```
Alternatively, in JSON format (though perhaps YAML is a bit more readable? YAML also allows comments)
```json
[
  {
    "name": "G_DRATE",
    "category": "parameter",
    "times-cols": [
      "REG",
      "DATAYEAR",
      "CUR",
      "VALUE"
    ],
    "xl-cols": [
      "Region",
      "Year",
      "Curr",
      "VALUE"
    ],
    "filter-attribute": "G_DRATE"
  }
]
```

A benefit of having a unified file is that it is less likely that an entity will be in one and not another, a bug that we've seen e.g. in:
https://github.com/etsap-TIMES/times-excel-reader/pull/102#issuecomment-1675953202 (cc @olejandro )
